# Generated by Django 3.2.5 on 2021-07-03 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_id', models.CharField(max_length=20)),
                ('building', models.CharField(max_length=200)),
                ('teacher', models.CharField(max_length=200)),
            ],
        ),
    ]
